### ISSUE TITLE
h2 mv.db file is locked

### ISSUE THREAD

**Issue by ZihengSun** [ESIPFed/Geoweaver#563]
```
2024-09-07 22:07:25.602671-04:00 database: flush
org.h2.message.DbException: General error: "org.h2.mvstore.MVStoreException: The file is locked: /ho$
        at org.h2.message.DbException.get(DbException.java:212)
        at org.h2.message.DbException.convert(DbException.java:407)
        at org.h2.mvstore.db.Store.lambda$new$0(Store.java:122)
        at org.h2.mvstore.MVStore.handleException(MVStore.java:1546)
        at org.h2.mvstore.MVStore.panic(MVStore.java:371)
        at org.h2.mvstore.MVStore.<init>(MVStore.java:291)
        at org.h2.mvstore.MVStore$Builder.open(MVStore.java:2035)
        at org.h2.mvstore.db.Store.<init>(Store.java:133)
        at org.h2.engine.Database.<init>(Database.java:326)
        at org.h2.engine.Engine.openSession(Engine.java:92)
        at org.h2.engine.Engine.openSession(Engine.java:222)
        at org.h2.engine.Engine.createSession(Engine.java:201)
        at org.h2.engine.SessionRemote.connectEmbeddedOrServer(SessionRemote.java:343)
        at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:125)
        at org.h2.util.JdbcUtils.getConnection(JdbcUtils.java:288)
        at org.h2.util.JdbcUtils.getConnection(JdbcUtils.java:270)
        at org.h2.tools.Shell.runTool(Shell.java:146)
        at org.h2.tools.Shell.main(Shell.java:80)
Caused by: org.h2.jdbc.JdbcSQLNonTransientException: General error: "org.h2.mvstore.MVStoreException$
        at org.h2.message.DbException.getJdbcSQLException(DbException.java:566)
        at org.h2.message.DbException.getJdbcSQLException(DbException.java:489)
        ... 18 more
Caused by: org.h2.mvstore.MVStoreException: The file is locked: /home/zsun/h2/gw.mv.db [2.2.224/7]
        at org.h2.mvstore.DataUtils.newMVStoreException(DataUtils.java:996)
        at org.h2.mvstore.SingleFileStore.lockFileChannel(SingleFileStore.java:143)
        at org.h2.mvstore.SingleFileStore.open(SingleFileStore.java:117)
        at org.h2.mvstore.SingleFileStore.open(SingleFileStore.java:81)
        at org.h2.mvstore.MVStore.<init>(MVStore.java:286)
        ... 12 more

```

**Comment by ZihengSun** [comment]
Temporary solution is to copy the h2 files to another location. Remove the original files, and move the files back, and restart Geoweaver.

```
mkdir -p /tmp/geoweaver_h2_bak/
cp ~/h2/* /tmp/geoweaver_h2_bak/
rm -rf ~/h2/*
cp  /tmp/geoweaver_h2_bak/* ~/h2/
gw restart
```

**Comment by ZihengSun** [comment]
This is an issue when you are running Geoweaver on multiple login nodes which are using the same DB at the same time. You have to stop the running Geoweaver on the other nodes before you can unlock this. Or you can assign each login Node to use a separate DB profile.
